In [79]:
import pandas as pd

ch = pd.read_csv("chicago.csv")
la = pd.read_csv("losangeles.csv")
ny = pd.read_csv("nycity.csv")
sf = pd.read_csv("sanfrancisco.csv")

In [80]:
ch["Description"] = ch["Primary Type"] + " - " + ch["Description"]
ch = ch[["Description", "Latitude", "Longitude", "Time", "type"]]
ch["City"] = "Chicago"
ch

,Description,Latitude,Longitude,Time,type,City
0,BATTERY - DOMESTIC BATTERY SIMPLE,41.864073,-87.706819,1900-01-01 23:40:00,2,Chicago
1,BATTERY - DOMESTIC BATTERY SIMPLE,41.782922,-87.604363,1900-01-01 21:40:00,2,Chicago
2,PUBLIC PEACE VIOLATION - RECKLESS CONDUCT,41.894908,-87.758372,1900-01-01 23:31:00,2,Chicago
3,BATTERY - SIMPLE,41.885687,-87.749516,1900-01-01 22:10:00,2,Chicago
4,THEFT - $500 AND UNDER,41.886297,-87.761751,1900-01-01 22:00:00,4,Chicago
...,...,...,...,...,...,...
250727,BATTERY - DOMESTIC BATTERY SIMPLE,41.849222,-87.691556,1900-01-01 23:33:00,2,Chicago
250728,CRIMINAL DAMAGE - TO PROPERTY,41.760744,-87.633335,1900-01-01 23:30:00,4,Chicago
250729,BATTERY - AGGRAVATED: HANDGUN,41.779235,-87.685207,1900-01-01 00:15:00,2,Chicago
250730,BATTERY - DOMESTIC BATTERY SIMPLE,41.745252,-87.552773,1900-01-01 21:07:00,2,Chicago
250731,OTHER OFFENSE - OTHER WEAPONS VIOLATION,41.758309,-87.620658,1900-01-01 23:38:00,1,Chicago

In [81]:
# Rename Crm Cd Desc to Description
la = la.rename(columns={"Crm Cd Desc": "Description"})
la = la[["Description", "Latitude", "Longitude", "Time", "type"]]
la["City"] = "Los Angeles"
la

,Description,Latitude,Longitude,Time,type,City
0,BATTERY - SIMPLE ASSAULT,34.0141,-118.2978,1900-01-01 22:30:00,624.0,Los Angeles
1,BATTERY - SIMPLE ASSAULT,34.0459,-118.2545,1900-01-01 03:30:00,624.0,Los Angeles
2,VANDALISM - MISDEAMEANOR ($399 OR UNDER),33.9739,-118.2630,1900-01-01 12:30:00,745.0,Los Angeles
3,VANDALISM - MISDEAMEANOR ($399 OR UNDER),34.1685,-118.4019,1900-01-01 17:30:00,745.0,Los Angeles
4,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",34.2198,-118.4468,1900-01-01 04:15:00,740.0,Los Angeles
...,...,...,...,...,...,...
196767,VEHICLE - STOLEN,34.0980,-118.3623,1900-01-01 12:00:00,510.0,Los Angeles
196768,THEFT OF IDENTITY,33.7270,-118.3242,1900-01-01 12:55:00,354.0,Los Angeles
196769,INTIMATE PARTNER - SIMPLE ASSAULT,34.0422,-118.4696,1900-01-01 16:00:00,626.0,Los Angeles
196770,ROBBERY,34.1940,-118.3943,1900-01-01 20:45:00,210.0,Los Angeles
196771,INTIMATE PARTNER - SIMPLE ASSAULT,33.9619,-118.4455,1900-01-01 21:00:00,626.0,Los Angeles

In [82]:
ny["Description"] = ny["OFNS_DESC"] + " - " + ny["LAW_CAT_CD"]
ny = ny[["Description", "Latitude", "Longitude", "Time", "type"]]
ny["City"] = "New York"
ny

,Description,Latitude,Longitude,Time,type,City
0,GRAND LARCENY - FELONY,40.771620,-73.990456,1900-01-01 20:51:00,109,New York
1,CRIMINAL MISCHIEF & RELATED OF - MISDEMEANOR,40.812317,-73.896361,1900-01-01 00:01:00,351,New York
2,ASSAULT 3 & RELATED OFFENSES - MISDEMEANOR,40.723595,-73.988201,1900-01-01 23:30:00,344,New York
3,FORGERY - FELONY,40.716116,-73.811905,1900-01-01 00:01:00,113,New York
4,GRAND LARCENY - FELONY,40.806480,-73.960206,1900-01-01 13:00:00,109,New York
...,...,...,...,...,...,...
467753,CRIMINAL MISCHIEF & RELATED OF - MISDEMEANOR,40.658884,-73.923574,1900-01-01 00:01:00,351,New York
467754,OFFENSES AGAINST THE PERSON - MISDEMEANOR,40.865558,-73.861563,1900-01-01 00:00:00,355,New York
467755,CRIMINAL MISCHIEF & RELATED OF - MISDEMEANOR,40.681050,-73.914106,1900-01-01 00:00:00,351,New York
467756,PETIT LARCENY - MISDEMEANOR,40.601700,-74.192807,1900-01-01 00:00:00,341,New York
467757,GRAND LARCENY - FELONY,40.643843,-73.948826,1900-01-01 00:00:00,109,New York

In [83]:
sf["Description"] = sf["Category"] + " - " + sf["Descript"]
sf = sf[["Description", "Latitude", "Longitude", "Time", "type"]]
sf["City"] = "San Francisco"
sf

,Description,Latitude,Longitude,Time,type,City
0,LARCENY/THEFT - GRAND THEFT PICKPOCKET,37.760801,-122.435563,1900-01-01 23:30:00,1.0,San Francisco
1,LARCENY/THEFT - GRAND THEFT FROM LOCKED AUTO,37.800037,-122.433575,1900-01-01 23:30:00,1.0,San Francisco
2,VEHICLE THEFT - STOLEN AUTOMOBILE,37.786834,-122.412777,1900-01-01 23:30:00,1.0,San Francisco
3,ASSAULT - AGGRAVATED ASSAULT WITH A DEADLY WEAPON,37.773641,-122.421701,1900-01-01 23:30:00,1.0,San Francisco
4,ASSAULT - INFLICT INJURY ON COHABITEE,37.773641,-122.421701,1900-01-01 23:30:00,1.0,San Francisco
...,...,...,...,...,...,...
150367,"BURGLARY - BURGLARY OF APARTMENT HOUSE, ATT FO...",37.773613,-122.426556,1900-01-01 00:01:00,1.0,San Francisco
150368,VEHICLE THEFT - STOLEN AUTOMOBILE,37.733790,-122.393906,1900-01-01 00:01:00,1.0,San Francisco
150369,MISSING PERSON - MISSING JUVENILE,37.721411,-122.445147,1900-01-01 00:01:00,1.0,San Francisco
150370,OTHER OFFENSES - FAILURE TO REGISTER AS SEX OF...,37.775421,-122.403405,1900-01-01 00:01:00,1.0,San Francisco
150371,LARCENY/THEFT - GRAND THEFT FROM LOCKED AUTO,37.732616,-122.393243,1900-01-01 00:01:00,1.0,San Francisco

In [84]:
# Are column names the same for all datasets?
print(ch.columns)
print(la.columns)
print(ny.columns)
print(sf.columns)

df = pd.concat([ch, la, ny, sf])

Index(['Description', 'Latitude', 'Longitude', 'Time', 'type', 'City'], dtype='object')
Index(['Description', 'Latitude', 'Longitude', 'Time', 'type', 'City'], dtype='object')
Index(['Description', 'Latitude', 'Longitude', 'Time', 'type', 'City'], dtype='object')
Index(['Description', 'Latitude', 'Longitude', 'Time', 'type', 'City'], dtype='object')

In [86]:
df.to_csv("crime_data.csv", index=False)

In [114]:
df = pd.read_csv("sanfrancisco.csv")
df

,Category,Descript,Resolution,Latitude,Longitude,Time,type
0,LARCENY/THEFT,GRAND THEFT PICKPOCKET,NONE,37.760801,-122.435563,1900-01-01 23:30:00,1.0
1,LARCENY/THEFT,GRAND THEFT FROM LOCKED AUTO,NONE,37.800037,-122.433575,1900-01-01 23:30:00,1.0
2,VEHICLE THEFT,STOLEN AUTOMOBILE,NONE,37.786834,-122.412777,1900-01-01 23:30:00,1.0
3,ASSAULT,AGGRAVATED ASSAULT WITH A DEADLY WEAPON,"ARREST, BOOKED",37.773641,-122.421701,1900-01-01 23:30:00,1.0
4,ASSAULT,INFLICT INJURY ON COHABITEE,"ARREST, BOOKED",37.773641,-122.421701,1900-01-01 23:30:00,1.0
...,...,...,...,...,...,...,...
150367,BURGLARY,"BURGLARY OF APARTMENT HOUSE, ATT FORCIBLE ENTRY",NONE,37.773613,-122.426556,1900-01-01 00:01:00,1.0
150368,VEHICLE THEFT,STOLEN AUTOMOBILE,NONE,37.733790,-122.393906,1900-01-01 00:01:00,1.0
150369,MISSING PERSON,MISSING JUVENILE,NONE,37.721411,-122.445147,1900-01-01 00:01:00,1.0
150370,OTHER OFFENSES,FAILURE TO REGISTER AS SEX OFFENDER,"ARREST, BOOKED",37.775421,-122.403405,1900-01-01 00:01:00,1.0
150371,LARCENY/THEFT,GRAND THEFT FROM LOCKED AUTO,NONE,37.732616,-122.393243,1900-01-01 00:01:00,1.0

In [108]:
df["Time"] = pd.to_datetime(df["Time"])

In [109]:
import datetime

# Print the range of dates in Time column
print(df['Time'].dt.date.min())
print(df['Time'].dt.date.max())

1900-01-01
1900-01-01